### ISSUE TITLE
Packer crash with EOF

### ISSUE THREAD

**Issue by jsturtevant** [hashicorp/packer-plugin-azure#130]
#### Overview of the Issue

Got an error when running packer. `panic: runtime error: invalid memory address or nil pointer dereference` logs below.

#### Reproduction Steps

This hasn't reproduce every time.  The build of the VM completed but during deletion there was a failure. Full logs are https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_image-builder/661/pull-azure-sigs/1419716032993431552/build-log.txt

### Plugin and Packer version

From `packer version`

packer_1.7.2

### Operating system and Environment details

packer is run on linux built with WS 2019 ARM builder.

### Log Fragments and crash.log files

```
panic: runtime error: invalid memory address or nil pointer dereference
2021/07/26 18:34:04 packer-builder-azure-arm plugin: [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x1a933ce]
2021/07/26 18:34:04 packer-builder-azure-arm plugin: 
2021/07/26 18:34:04 packer-builder-azure-arm plugin: goroutine 571 [running]:
2021/07/26 18:34:04 packer-builder-azure-arm plugin: github.com/Azure/go-autorest/autorest/azure.(*Future).WaitForCompletionRef(0xc000c88cc0, 0x546d9c0, 0xc000847ac0, 0x53f6420, 0xc000b24720, 0x540e140, 0xc000f2ade0, 0xc000503b70, 0xc000b316e0, 0xdf8475800, ...)
2021/07/26 18:34:04 packer-builder-azure-arm plugin: 	/home/circleci/project/packer/vendor/github.com/Azure/go-autorest/autorest/azure/async.go:174 +0x54e
2021/07/26 18:34:04 packer-builder-azure-arm plugin: github.com/hashicorp/packer/builder/azure/arm.(*StepCaptureImage).captureImageFromVM(0xc0006ba200, 0x546d9c0, 0xc000847ac0, 0xc0006de618, 0x18, 0xc0009e2460, 0x1c, 0xc00079bfc0, 0xc00014fec0, 0x29)
2021/07/26 18:34:04 packer-builder-azure-arm plugin: 	/home/circleci/project/packer/builder/azure/arm/step_capture_image.go:57 +0x225
2021/07/26 18:34:04 packer-builder-azure-arm plugin: github.com/hashicorp/packer/builder/azure/arm.(*StepCaptureImage).Run(0xc0006ba200, 0x546d9c0, 0xc000847ac0, 0x546e360, 0xc000c4a990, 0x0)
2021/07/26 18:34:04 packer-builder-azure-arm plugin: 	/home/circleci/project/packer/builder/azure/arm/step_capture_image.go:93 +0x922
2021/07/26 18:34:04 packer-builder-azure-arm plugin: github.com/hashicorp/packer-plugin-sdk/multistep.(*BasicRunner).Run(0xc00057c9f0, 0x546d9c0, 0xc000847ac0, 0x546e360, 0xc000c4a990)
2021/07/26 18:34:04 packer-builder-azure-arm plugin: 	/home/circleci/project/packer/vendor/github.com/hashicorp/packer-plugin-sdk/multistep/basic_runner.go:70 +0x234
2021/07/26 18:34:04 packer-builder-azure-arm plugin: github.com/hashicorp/packer/builder/azure/arm.(*Builder).Run(0xc00018aa80, 0x546d9c0, 0xc000847ac0, 0x54852a8, 0xc000f2a060, 0x53f8da0, 0xc0001b6060, 0x0, 0x0, 0x0, ...)
2021/07/26 18:34:04 packer-builder-azure-arm plugin: 	/home/circleci/project/packer/builder/azure/arm/builder.go:283 +0x14f0
2021/07/26 18:34:04 packer-builder-azure-arm plugin: github.com/hashicorp/packer-plugin-sdk/rpc.(*BuilderServer).Run(0xc000846040, 0x1, 0xc0008c6b5c, 0x0, 0x0)
2021/07/26 18:34:04 packer-builder-azure-arm plugin: 	/home/circleci/project/packer/vendor/github.com/hashicorp/packer-plugin-sdk/rpc/builder.go:117 +0x1c4
2021/07/26 18:34:04 packer-builder-azure-arm plugin: reflect.Value.call(0xc0000c6540, 0xc00074a088, 0x13, 0x4dc3f51, 0x4, 0xc0006aaf08, 0x3, 0x3, 0x0, 0x0, ...)
2021/07/26 18:34:04 packer-builder-azure-arm plugin: 	/usr/local/go/src/reflect/value.go:476 +0x8e7
2021/07/26 18:34:04 packer-builder-azure-arm plugin: reflect.Value.Call(0xc0000c6540, 0xc00074a088, 0x13, 0xc0006c2f08, 0x3, 0x3, 0x0, 0x0, 0x0)
2021/07/26 18:34:04 packer-builder-azure-arm plugin: 	/usr/local/go/src/reflect/value.go:337 +0xb9
2021/07/26 18:34:04 packer-builder-azure-arm plugin: net/rpc.(*service).call(0xc000846080, 0xc00030e190, 0xc0001a6040, 0xc0001a6050, 0xc0008b6180, 0xc00020a420, 0x3f2af60, 0xc0008c6b58, 0x18a, 0x3e2a5e0, ...)
2021/07/26 18:34:04 packer-builder-azure-arm plugin: 	/usr/local/go/src/net/rpc/server.go:377 +0x189
2021/07/26 18:34:04 packer-builder-azure-arm plugin: created by net/rpc.(*Server).ServeCodec
2021/07/26 18:34:04 packer-builder-azure-arm plugin: 	/usr/local/go/src/net/rpc/server.go:474 +0x44d
2021/07/26 18:34:04 [ERR] Error decoding response stream 23: EOF
2021/07/26 18:34:04 [ERR] Error decoding response stream 20: EOF
2021/07/26 18:34:04 [ERR] Error decoding response stream 29: EOF
2021/07/26 18:34:04 [ERR] Error decoding response stream 26: EOF
2021/07/26 18:34:04 [INFO] (telemetry) ending azure-arm
2021/07/26 18:34:04 /home/prow/go/src/sigs.k8s.io/image-builder/images/capi/.local/bin/packer: plugin process exited
2021/07/26 18:34:04 ui error: [1;31mBuild 'sig-windows-2019' errored after 38 minutes 44 seconds: unexpected EOF[0m
2021/07/26 18:34:04 ui: 
==> Wait completed after 38 minutes 44 seconds
2021/07/26 18:34:04 machine readable: error-count []string{"1"}
2021/07/26 18:34:04 ui error: 
==> Some builds didn't complete successfully and had errors:
2021/07/26 18:34:04 machine readable: sig-windows-2019,error []string{"unexpected EOF"}
2021/07/26 18:34:04 ui error: --> sig-windows-2019: unexpected EOF
2021/07/26 18:34:04 ui: 
==> Builds finished but no artifacts were created.
2021/07/26 18:34:04 [INFO] (telemetry) Finalizing.
2021/07/26 18:34:04 waiting for all plugin processes to complete...
2021/07/26 18:34:04 /root/.packer.d/plugins/packer-provisioner-goss: plugin process exited
2021/07/26 18:34:04 /home/prow/go/src/sigs.k8s.io/image-builder/images/capi/.local/bin/packer: plugin process exited
2021/07/26 18:34:04 /home/prow/go/src/sigs.k8s.io/image-builder/images/capi/.local/bin/packer: plugin process exited
2021/07/26 18:34:04 /home/prow/go/src/sigs.k8s.io/image-builder/images/capi/.local/bin/packer: plugin process exited
2021/07/26 18:34:04 /home/prow/go/src/sigs.k8s.io/image-builder/images/capi/.local/bin/packer: plugin process exited
2021/07/26 18:34:04 /home/prow/go/src/sigs.k8s.io/image-builder/images/capi/.local/bin/packer: plugin process exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Packer crashed! This is always indicative of a bug within Packer.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Packer[1] so that we can fix this.
```

**Comment by jsturtevant** [comment]
Looking further this looks to be a duplicate of https://github.com/hashicorp/packer-plugin-azure/issues/41.

The main issue being that the `shared_image_gallery_destination` config was the same across to different builders.
