### ISSUE TITLE
Crash invalid memory address

### ISSUE THREAD

**Issue by spencer-cdw** [hashicorp/packer-plugin-azure#276]
Attached is a crash.log (with redacted ip addresses and resource groups) for a windows 2019 build using azure-arm

These builds have succeeded many times in the past, however this crash is happening more and more frequently (but not every time). 

The significant crash lines are

```
==> azure-arm.win2019: The resource group was not created by Packer, not deleting ...[0m
2023/02/27 15:54:24 packer-builder-azure-arm plugin: panic: runtime error: invalid memory address or nil pointer dereference
2023/02/27 15:54:24 packer-builder-azure-arm plugin: [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x208245a]
```

Additional logs. 

https://gist.github.com/spencer-cdw/ef04ab25c36c64a4b086220b90c6e689#file-crash-log

**Comment by JenGoldstrich** [comment]
Hey Spencer, looking at your gist
```

2023/02/27 15:54:08 ui: [1;32m2023-02-27T15:54:08Z: ==> azure-arm.win2019: Removing the created Deployment object: 'kvpkrdpibcda8eynl'[0m
2023/02/27 15:54:08 packer-builder-azure-arm plugin: Azure response status="200 OK" method="DELETE" request="https://management.azure.com/subscriptions/<sensitive>/resourceGroups/GIM-Build-Images-RG/providers/Microsoft.KeyVault/vaults/REDACTED?api-version=2018-02-14" x-ms-request-id="11da6764-8c3a-465c-b17d-bffa2a575da7" body=""
2023/02/27 15:54:08 packer-builder-azure-arm plugin: Azure request method="DELETE" request="https://management.azure.com/subscriptions/<sensitive>/resourcegroups/GIM-Build-Images-RG/providers/Microsoft.Resources/deployments/kvpkrdpibcda8eynl?api-version=2018-02-01" body=""
2023/02/27 15:54:09 packer-builder-azure-arm plugin: Azure response status="202 Accepted" method="DELETE" request="https://management.azure.com/subscriptions/<sensitive>/resourcegroups/GIM-Build-Images-RG/providers/Microsoft.Resources/deployments/kvpkrdpibcda8eynl?api-version=2018-02-01" x-ms-request-id="79600aae-2b8b-4d34-94d9-acce41d004ce" body=""
2023/02/27 15:54:24 packer-builder-azure-arm plugin: Azure request request="https://management.azure.com/subscriptions/<sensitive>/operationresults/eyJqb2JJZCI6IkRlcGxveW1lbnREZWxldGlvbkpvYi1HTlMtR0lNOjJEQlVJTEQ6MkRJTUFHRVM6MkRSRy1LVlBLUkRQSUJDREE4RVlOTC0iLCJqb2JMb2NhdGlvbiI6Im5vcnRoY2VudHJhbHVzIn0?api-version=2018-02-01" body="" method="GET"
2023/02/27 15:54:24 packer-builder-azure-arm plugin: Azure response status="204 No Content" method="GET" request="https://management.azure.com/subscriptions/<sensitive>/operationresults/eyJqb2JJZCI6IkRlcGxveW1lbnREZWxldGlvbkpvYi1HTlMtR0lNOjJEQlVJTEQ6MkRJTUFHRVM6MkRSRy1LVlBLUkRQSUJDREE4RVlOTC0iLCJqb2JMb2NhdGlvbiI6Im5vcnRoY2VudHJhbHVzIn0?api-version=2018-02-01" x-ms-request-id="0450d57f-5f50-488f-8b75-223000e0f4bf" body=""
2023/02/27 15:54:24 ui: [1;32m2023-02-27T15:54:24Z: ==> azure-arm.win2019: 
==> azure-arm.win2019: The resource group was not created by Packer, not deleting ...[0m
2023/02/27 15:54:24 packer-builder-azure-arm plugin: panic: runtime error: invalid memory address or nil pointer dereference
2023/02/27 15:54:24 packer-builder-azure-arm plugin: [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x208245a]
2023/02/27 15:54:24 packer-builder-azure-arm plugin: 
2023/02/27 15:54:24 packer-builder-azure-arm plugin: goroutine 145 [running]:
2023/02/27 15:54:24 packer-builder-azure-arm plugin: github.com/Azure/go-autorest/autorest/azure.(*Future).WaitForCompletionRef(0xc0011fd850, {0x59e2128?, 0xc000e9ff40?}, {{0x59a1160, 0xc00106a580}, {0x59c5960, 0xc00037e5d0}, 0xc000128fc0, 0xc001066160, 0x6fc23ac00, ...})
2023/02/27 15:54:24 packer-builder-azure-arm plugin: 	github.com/Azure/go-autorest/autorest@v0.11.19/azure/async.go:228 +0x65a
2023/02/27 15:54:24 packer-builder-azure-arm plugin: github.com/hashicorp/packer-plugin-azure/builder/azure/arm.(*StepCaptureImage).captureImageFromVM(0xc00084a440, {0x59e2128, 0xc000e9ff40}, {0xc000514fc0?, 0x22b4610?}, {0xc000e831d0?, 0xc001390930?}, 0x30?)
2023/02/27 15:54:24 packer-builder-azure-arm plugin: 	github.com/hashicorp/packer-plugin-azure@v1.4.0/builder/azure/arm/step_capture_image.go:57 +0x20a
``` 
This panic looks like its coming from go-autorest, we have a pinned issue here https://github.com/hashicorp/packer-plugin-azure/issues/243 but we are having to update away from go-autorest as Microsoft is deprecating it so I believe your issue will likely be resolved when we move off of go-autorest, but please follow that issue for updates on the SDK upgrade

**Comment by JenGoldstrich** [comment]
Hey @spencer-cdw just to come back to this issue with a bit more knowledge now

```
2023/02/27 15:49:07 packer-builder-azure-arm plugin: Azure response request="https://management.azure.com/subscriptions/<sensitive>/resourceGroups/GIM-Images-RG/providers/Microsoft.Compute/images/jeremyguthriewindows-2019-cis1-20230227-60?api-version=2021-11-01" x-ms-request-id="22503c31-b350-4b4b-9664-d89b0e9ae57d" body="{\r\n  \"error\": {\r\n    \"code\": \"PropertyChangeNotAllowed\",\r\n    \"message\": \"Changing property 'sourceVirtualMachine' is not allowed.\",\r\n    \"target\": \"sourceVirtualMachine\"\r\n  }\r\n}" status="409 Conflict" method="PUT"
2023/02/27 15:49:07 ui: [1;32m2023-02-27T15:49:07Z: ==> azure-arm.win2019: ERROR: -> PropertyChangeNotAllowed : Changing property 'sourceVirtualMachine' is not allowed.
==> azure-arm.win2019:[0m
```

The cause of this build failure is not the panic related to an invalid memory address, that's just a red herring error thrown by go-autorest (upstream Azure dependency that is in the process of being deprecated) when this specific error case related to changing the sourceVirtualMachine is actually what's failing, go-autorest.  Once the Managed Image is created it's VM can not be updated.   This issue will always occur regardless of any changes on the plugin, even on new SDK versions this error would still occur, it just would hopefully not panic

Since this is a CI build I believe based on what you've said above what is most likely happening here is that builds are trying to modify the same managed image, even when using the -force command to delete the previous managed image depending on when the two builds are started they could be trying to modify the same Managed Image, which will lead to this error from the Azure API (see here for more information https://github.com/hashicorp/packer-plugin-azure/issues/190#issuecomment-1518087581)

My two recommended solutions are

1.) [Recommended] Switch to using Shared Image Gallery Destination only (requires plugin version 1.4.0+ https://github.com/hashicorp/packer-plugin-azure/releases/tag/v1.4.0, you can basically just remove `managed_image_name` and `managed_image_resource_group_name` from your template, this means you won't try and build a managed image at all and instead directly publish to Shared Image Gallery.  I would also recommend setting your version to be unique for each CI build by using a build/run number as your image version you use for the Shared image Gallery, that way you won't run into conflicts

New features on the Azure API side are only limited to directly publishing to Compute Image Galleries, several new features we've added on the plugin in the last few months (Arm64 images, Disk Encryption with a customer managed key) are only supported on this new type of build.

2.) Limit your CI to one concurrent build and make sure that a build finishes fully before another one that modifies the same managed image is changed

Please let me know if you have any other questions or if this helps resolve this failure for you!

**Comment by JenGoldstrich** [comment]
Closing due to inactivity, please re-open if you are still experiencing this issue and the above solution does not remediate it for you
